import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "خرید و دانلود کتاب متنی، صوتی با فیدیبو",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="icon" href="./img/logo.png" sizes="any" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
